### ISSUE TITLE
New tenant error

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1060]
Appears to create the tenant and run the migrations, but then this:
```
...
web_1          |  OK
web_1          |   Applying tenant.0006_auto_20220116_1955...
web_1          |  OK
web_1          |   Applying tenant.0007_django_tenants_migration...
web_1          |  OK
web_1          |   Applying tenant.0008_populate_tenant_domain...
web_1          |  OK
web_1          |   Applying utilities.0001_initial...
web_1          |  OK
web_1          | Traceback (most recent call last):
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
web_1          |     return self.connection.commit()
web_1          | psycopg2.errors.ForeignKeyViolation: insert or update on table "django_admin_log" violates foreign key constraint "django_admin_log_user_id_c564eba6_fk_auth_user_id"
web_1          | DETAIL:  Key (user_id)=(6) is not present in table "auth_user".
web_1          | 
web_1          | 
web_1          | The above exception was the direct cause of the following exception:
web_1          | 
web_1          | Traceback (most recent call last):
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
web_1          |     response = get_response(request)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
web_1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
web_1          |     return self.admin_site.admin_view(view)(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
web_1          |     response = view_func(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
web_1          |     response = view_func(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
web_1          |     return view(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1657, in add_view
web_1          |     return self.changeform_view(request, None, form_url, extra_context)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
web_1          |     return bound_method(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
web_1          |     response = view_func(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1540, in changeform_view
web_1          |     return self._changeform_view(request, object_id, form_url, extra_context)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/transaction.py", line 246, in __exit__
web_1          |     connection.commit()
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
web_1          |     return func(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 266, in commit
web_1          |     self._commit()
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
web_1          |     return self.connection.commit()
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
web_1          |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
web_1          |     return self.connection.commit()
web_1          | django.db.utils.IntegrityError: insert or update on table "django_admin_log" violates foreign key constraint "django_admin_log_user_id_c564eba6_fk_auth_user_id"
web_1          | DETAIL:  Key (user_id)=(6) is not present in table "auth_user".
web_1          | 
web_1          | 
web_1          | During handling of the above exception, another exception occurred:
web_1          | 
web_1          | Traceback (most recent call last):
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1          |     return self.cursor.execute(sql, params)
web_1          | psycopg2.errors.UndefinedTable: relation "siteconfig_siteconfig" does not exist
web_1          | LINE 1: ...ter"."last_day", "courses_semester"."closed" FROM "siteconfi...
web_1          |                                                              ^
web_1          | 
web_1          | 
web_1          | The above exception was the direct cause of the following exception:

...
```

**Comment by tylerecouture** [comment]
For some reason adding via the deck/new view works.  What's going on?
