### ISSUE TITLE
Error adding new tenants

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1151]
When adding a new tenant on staging, getting this error.  Not sure which commit is causing this, I'll add more details as I find.

> IntegrityError at /admin/tenant/tenant/add/
> 
> insert or update on table "django_admin_log" violates foreign key constraint "django_admin_log_user_id_c564eba6_fk_auth_user_id"
> DETAIL:  Key (user_id)=(5) is not present in table "auth_user".

```
web_1          |   Applying tenant.0006_auto_20220116_1955...
web_1          |  OK
web_1          |   Applying tenant.0007_django_tenants_migration...
web_1          |  OK
web_1          |   Applying tenant.0008_populate_tenant_domain...
web_1          |  OK
web_1          |   Applying tenant.0009_auto_20220809_1959...
web_1          |  OK
web_1          |   Applying utilities.0001_initial...
web_1          |  OK
web_1          |   Applying utilities.0002_alter_menuitem_url...
web_1          |  OK
web_1          | Internal Server Error: /admin/tenant/tenant/add/
web_1          | Traceback (most recent call last):
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
web_1          |     return self.connection.commit()
web_1          | psycopg2.errors.ForeignKeyViolation: insert or update on table "django_admin_log" violates foreign key constraint "django_admin_log_user_id_c564eba6_fk_auth_user_id"
web_1          | DETAIL:  Key (user_id)=(5) is not present in table "auth_user".
web_1          | 
web_1          | 
web_1          | The above exception was the direct cause of the following exception:
web_1          | 
web_1          | Traceback (most recent call last):
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
web_1          |     response = get_response(request)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
web_1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
web_1          |     return self.admin_site.admin_view(view)(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
web_1          |     response = view_func(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
web_1          |     response = view_func(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
web_1          |     return view(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1657, in add_view
web_1          |     return self.changeform_view(request, None, form_url, extra_context)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
web_1          |     return bound_method(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
web_1          |     response = view_func(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1540, in changeform_view
web_1          |     return self._changeform_view(request, object_id, form_url, extra_context)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/transaction.py", line 246, in __exit__
web_1          |     connection.commit()
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
web_1          |     return func(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 266, in commit
web_1          |     self._commit()
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
web_1          |     return self.connection.commit()
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
web_1          |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
web_1          |     return self.connection.commit()
web_1          | django.db.utils.IntegrityError: insert or update on table "django_admin_log" violates foreign key constraint "django_admin_log_user_id_c564eba6_fk_auth_user_id"
web_1          | DETAIL:  Key (user_id)=(5) is not present in table "auth_user".
web_1          | 
web_1          | Internal Server Error: /admin/tenant/tenant/add/
web_1          | Traceback (most recent call last):
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
web_1          |     return self.connection.commit()
web_1          | psycopg2.errors.ForeignKeyViolation: insert or update on table "django_admin_log" violates foreign key constraint "django_admin_log_user_id_c564eba6_fk_auth_user_id"
web_1          | DETAIL:  Key (user_id)=(5) is not present in table "auth_user".
web_1          | 
web_1          | 
web_1          | The above exception was the direct cause of the following exception:
web_1          | 
web_1          | Traceback (most recent call last):
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
web_1          |     response = get_response(request)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
web_1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
web_1          |     return self.admin_site.admin_view(view)(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
web_1          |     response = view_func(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
web_1          |     response = view_func(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
web_1          |     return view(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1657, in add_view
web_1          |     return self.changeform_view(request, None, form_url, extra_context)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
web_1          |     return bound_method(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
web_1          |     response = view_func(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1540, in changeform_view
web_1          |     return self._changeform_view(request, object_id, form_url, extra_context)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/transaction.py", line 246, in __exit__
web_1          |     connection.commit()
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
web_1          |     return func(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 266, in commit
web_1          |     self._commit()
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
web_1          |     return self.connection.commit()
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
web_1          |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
web_1          |     return self.connection.commit()
web_1          | django.db.utils.IntegrityError: insert or update on table "django_admin_log" violates foreign key constraint "django_admin_log_user_id_c564eba6_fk_auth_user_id"
web_1          | DETAIL:  Key (user_id)=(5) is not present in table "auth_user".
web_1          | 
web_1          | [pid: 44|app: 0|req: 12/117] 24.108.72.231 () {58 vars in 1193 bytes} [Wed Aug 10 10:26:35 2022] POST /admin/tenant/tenant/add/ => generated 147134 bytes in 8370 msecs (HTTP/2.0 500) 8 headers in 514 bytes (1 switches on core 0)
web_1          | Internal Server Error: /admin/auth/user/4/delete/
web_1          | Traceback (most recent call last):
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1          |     return self.cursor.execute(sql, params)
web_1          | psycopg2.errors.UndefinedTable: relation "account_emailaddress" does not exist
web_1          | LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "account_e...
web_1          |                                                              ^
web_1          | 
web_1          | 
web_1          | The above exception was the direct cause of the following exception:
web_1          | 
web_1          | Traceback (most recent call last):
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
web_1          |     response = get_response(request)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
web_1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
web_1          |     return self.admin_site.admin_view(view)(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
web_1          |     response = view_func(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
web_1          |     response = view_func(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
web_1          |     return view(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
web_1          |     return bound_method(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
web_1          |     response = view_func(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1851, in delete_view
web_1          |     return self._delete_view(request, object_id, extra_context)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1872, in _delete_view
web_1          |     deleted_objects, model_count, perms_needed, protected = self.get_deleted_objects([obj], request)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1846, in get_deleted_objects
web_1          |     return get_deleted_objects(objs, request, self.admin_site)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 119, in get_deleted_objects
web_1          |     collector.collect(objs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 182, in collect
web_1          |     return super().collect(objs, source_attr=source_attr, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/deletion.py", line 295, in collect
web_1          |     if sub_objs:
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 284, in __bool__
web_1          |     self._fetch_all()
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
web_1          |     self._result_cache = list(self._iterable_class(self))
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
web_1          |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
web_1          |     cursor.execute(sql, params)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
web_1          |     return super().execute(sql, params)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
web_1          |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
web_1          |     return executor(sql, params, many, context)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1          |     return self.cursor.execute(sql, params)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
web_1          |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1          |     return self.cursor.execute(sql, params)
web_1          | django.db.utils.ProgrammingError: relation "account_emailaddress" does not exist
web_1          | LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "account_e...
web_1          |                                                              ^
web_1          | 
web_1          | Internal Server Error: /admin/auth/user/4/delete/
web_1          | Traceback (most recent call last):
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1          |     return self.cursor.execute(sql, params)
web_1          | psycopg2.errors.UndefinedTable: relation "account_emailaddress" does not exist
web_1          | LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "account_e...
web_1          |                                                              ^
web_1          | 
web_1          | 
web_1          | The above exception was the direct cause of the following exception:
web_1          | 
web_1          | Traceback (most recent call last):
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
web_1          |     response = get_response(request)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
web_1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
web_1          |     return self.admin_site.admin_view(view)(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
web_1          |     response = view_func(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
web_1          |     response = view_func(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
web_1          |     return view(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
web_1          |     return bound_method(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
web_1          |     response = view_func(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1851, in delete_view
web_1          |     return self._delete_view(request, object_id, extra_context)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1872, in _delete_view
web_1          |     deleted_objects, model_count, perms_needed, protected = self.get_deleted_objects([obj], request)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1846, in get_deleted_objects
web_1          |     return get_deleted_objects(objs, request, self.admin_site)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 119, in get_deleted_objects
web_1          |     collector.collect(objs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 182, in collect
web_1          |     return super().collect(objs, source_attr=source_attr, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/deletion.py", line 295, in collect
web_1          |     if sub_objs:
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 284, in __bool__
web_1          |     self._fetch_all()
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
web_1          |     self._result_cache = list(self._iterable_class(self))
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
web_1          |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
web_1          |     cursor.execute(sql, params)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
web_1          |     return super().execute(sql, params)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
web_1          |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
web_1          |     return executor(sql, params, many, context)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1          |     return self.cursor.execute(sql, params)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
web_1          |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1          |     return self.cursor.execute(sql, params)
web_1          | django.db.utils.ProgrammingError: relation "account_emailaddress" does not exist
web_1          | LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "account_e...

```

**Comment by tylerecouture** [comment]
Tried: https://stackoverflow.com/a/34109293/2700631

with:
```
$ docker-compose -f docker-compose.yml -f docker-compose.prod.aws.yml exec web bash -c "./src/manage.py migrate admin 0001"


# Connect to RDS locally, then
bytedeck=> DROP TABLE django_admin_log;

# Response:
DROP TABLE
bytedeck=>

$ docker-compose -f docker-compose.yml -f docker-compose.prod.aws.yml exec web bash -c "src/manage.py sqlmigrate admin 0001"

# Copy output and paste into RDS:

bytedeck=> BEGIN;
--
-- Create model LogEntry
--
# ...
COMMIT

# Response:
bytedeck=>

$ docker-compose -f docker-compose.yml -f docker-compose.prod.aws.yml exec web bash -c "src/manage.py migrate admin"

```

**Comment by tylerecouture** [comment]
In [3]: from django.contrib.contenttypes.models import ContentType

In [4]: ContentType.objects.clear_cache()

Didn't work per https://github.com/bernardopires/django-tenant-schemas/issues/314#issuecomment-301029731

**Comment by thefoxwithin** [comment]
Is this a duplicate issue? https://github.com/bytedeck/bytedeck/issues/1060
