### ISSUE TITLE
Can't add an excluded day to semester through Semester/Update Semester

### ISSUE THREAD

**Issue by mattjmoore** [bytedeck/bytedeck#1241]
I tried to add a new excluded day to our semester calendar for the currently active semester running from Sep 7 to Nov 10.  I was not able to do this through the front end byte deck site.  When I entered the date Sept 19, 2022 (Memorial for QEII Holiday) from the calendar on the Update Semester page and hit update I got a "500 Server Error."
![image](https://user-images.githubusercontent.com/115576527/195162174-100d4b39-af36-4317-969a-d90ee369d999.png)

The new excluded date was successfully added by another staff member with "back end" access.

**Comment by tylerecouture** [comment]
Thanks for reporting this. I see the error, but I can't reproduce it.  Were you typing the date in or choosing it from the date selector widget?  Any more info you can provide will help us track down the bug. Thanks!

Error:

```
Internal Server Error: /courses/semesters/19/edit/

IntegrityError at /courses/semesters/19/edit/
null value in column "date_type_id" violates not-null constraint
DETAIL:  Failing row contains (230, 2022-09-19, null, 19, Queen Elizabeth Memorial Holiday).
```

**Comment by mattjmoore** [comment]
Hi,

I was choosing the date from the calendar widget.  I am pretty sure I did not try typing it in manually.  There's a chance I might have, but I am pretty sure I just used the widget.

Thanks for taking a look at it!

Matt

**Comment by jefcolbi** [comment]
Hi @tylerecouture 
Were you able to reproduce this bug ?

**Comment by tylerecouture** [comment]
Nope

**Comment by fjbagley** [comment]
This might be a Studio Tyee only issue at the moment. Still unable to add excluded dates on the front end. Just tried creating a new test semester and the issues remain.

**Comment by fjbagley** [comment]
I will add the excluded dates through django.

**Comment by tylerecouture** [comment]
**Error** being reported:


Internal Server Error: /courses/semesters/add/

IntegrityError at /courses/semesters/add/
null value in column "date_type_id" violates not-null constraint
DETAIL:  Failing row contains (256, 2023-09-13, null, 33, Test).

**Stacktrace**:

Exception Type: IntegrityError at /courses/semesters/add/
Exception Value: null value in column "date_type_id" violates not-null constraint
DETAIL:  Failing row contains (256, 2023-09-13, null, 33, Test).

Request information:
USER: fergus.bagley

GET: No GET data

POST:
csrfmiddlewaretoken = ''
first_day = '2023-09-11'
initial-first_day = '2023-09-11'
last_day = '2024-01-24'
initial-last_day = '2024-01-24'
form-TOTAL_FORMS = '2'
form-INITIAL_FORMS = '0'
form-MIN_NUM_FORMS = '0'
form-MAX_NUM_FORMS = '1000'
form-0-id = ''
form-0-DELETE = ''
form-0-date = '2023-09-13'
form-0-label = 'Test'
form-1-id = ''
form-1-DELETE = ''
form-1-date = ''
form-1-label = ''

FILES: No FILES data

**Comment by tylerecouture** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

The above exception (null value in column "date_type_id" violates not-null constraint
DETAIL:  Failing row contains (256, 2023-09-13, null, 33, Test).
) was the direct cause of the following exception:
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "./hackerspace_online/decorators.py", line 16, in wrapper
    return f(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/app/src/tenant/views.py", line 40, in wrapper
    return f(*args, **kwargs)
  File "/app/src/tenant/views.py", line 49, in dispatch
    return super().dispatch(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/src/courses/views.py", line 379, in post
    return self.form_valid(*forms)
  File "/app/src/courses/views.py", line 410, in form_valid
    formset.save()
  File "/usr/local/lib/python3.8/site-packages/django/forms/models.py", line 681, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "/usr/local/lib/python3.8/site-packages/django/forms/models.py", line 819, in save_new_objects
    self.new_objects.append(self.save_new(form, commit=commit))
  File "/usr/local/lib/python3.8/site-packages/django/forms/models.py", line 658, in save_new
    return form.save(commit=commit)
  File "/app/src/courses/forms.py", line 157, in save
    return excluded_date.save()  # formset saves the rest in its own function
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

**Comment by tylerecouture** [comment]
This may require surgery on this one tenant's schema, but need to figure out what migration got screwed up or what we need to change.

**Comment by fjbagley** [comment]
Thanks. We have been able to add excluded days via the backend for now.

**Comment by yujinyuz** [comment]
@tylerecouture 

Are there any tenants using the `ExcludeDate.date_type` ?

I see that it isn't being used in the frontend and not asking for the `date_type` input. I was thinking maybe we could just remove the field instead since it's not being used anyways.

<img width="1327" alt="image" src="https://github.com/bytedeck/bytedeck/assets/10972027/a0c04376-9e49-4c48-a4e2-bc873e12edda">

**Comment by tylerecouture** [comment]
Good plan. Let's remove it.

**Comment by tylerecouture** [comment]
@fjbagley can you verify this bug has been fixed for you guys?

**Comment by fjbagley** [comment]
Works now. Thank you!
