### ISSUE TITLE
get() returned more than one QuestSubmission

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1260]
Internal Server Error: /quests/submission/4574/

MultipleObjectsReturned at /quests/submission/4574/
get() returned more than one QuestSubmission -- it returned 2!

Request Method: GET
Request URL: http://edpb530.bytedeck.com/quests/submission/4574/

Related #869 ?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/src/tenant/views.py", line 37, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/src/quest_manager/views.py", line 1212, in submission
    return render(request, 'quest_manager/submission.html', context)
  File "/usr/local/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 195, in render
    return template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 517, in render
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 517, in <dictcomp>
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/app/src/quest_manager/models.py", line 962, in get_previous
    return QuestSubmission.objects.get(quest=self.quest, user=self.user, ordinal=self.ordinal - 1)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(

Exception Type: MultipleObjectsReturned at /quests/submission/4574/
Exception Value: get() returned more than one QuestSubmission -- it returned 2!
```

**Comment by jefcolbi** [comment]
@tylerecouture How can we reproduce this?

**Comment by tylerecouture** [comment]
@yujinyuz I'm going to split this into two issues:

1. Deal with the current issue dynamically (this issues)
2. Management command to fix existing data, then implement a unique constraint (new issue)

For this issue, to resolve the problem dynamically, we will need a method that can "fix" ordinals:
  1. Finds duplicate ordinals
  2. Assign one of them a new ordinal (max ordinal value + 1)
  3. Re-try

The thing about adding the unique constraint, is it doesn't solve the issue, which is somewhere, somehow, duplicate ordinals are being assigned, which shouldn't happen.  I think that code needs to be traced.

**Comment by tylerecouture** [comment]
![image](https://user-images.githubusercontent.com/10604391/213336967-29403caf-8efe-4cec-a515-f6f67f0850ed.png)

**Comment by yujinyuz** [comment]
@tylerecouture I'm not quite sure I understand what you mean by that. Could you explain further?

I also created a new PR to deal with this https://github.com/bytedeck/bytedeck/pull/1288

**Comment by tylerecouture** [comment]
@yujinyuz I'm just trying to figure out how the wring ordinal is being applied.  Within the code logic, how did two submissions both get ordinal 5? (screenshot above)

Note PR #1288 is failing tests.

**Comment by yujinyuz** [comment]
This is just a wild guess but since the default value of `ordinal` is 1, when the migration was applied to old submissions, they all had the default value.

**Comment by tylerecouture** [comment]
No, this is happening on new decks, screenshot above was from a decks, and doesn't explain why ordinal #5 was duplicated (screenshot) and yet ordinal #4 a couple days earlier was fine.

**Comment by yujinyuz** [comment]
Alright. I'll try to look into this one more time and see what I can find.

Seems to have happened around the fourth or fifth submission so I'll start from there

**Comment by tylerecouture** [comment]
I suspect you can reproduce it by doing something like this:

Complete a few of a repeating quest. Say 4 fo them (ordinals 1, 2, 3, 4)

Teacher: Approve #1 and 4, return 2 and 3.

Student: drop #2

Student, start #5, submit it.

**Comment by yujinyuz** [comment]
So, I tried to follow the steps you gave using the `Send your teacher a Message` quest..

Created 4 submissions.

Approved 1 and 4.

Returned 2 and 3.

Dropped 2.

Since submission 3 has been returned, when I try to start a new quest via `/quests/:quest-id/start/`, I get redirected to submission 3 since that was still not completed.
