### ISSUE TITLE
django check is failing:  ClearableFileInput doesn't support uploading multiple files.

### ISSUE THREAD

**Issue by yujinyuz** [bytedeck/bytedeck#1353]
Django 3.2.19 just released a security fix for `ClearableFileInput` and causes CI to fail

https://docs.djangoproject.com/en/4.2/releases/3.2.19/

The temporary fix seems to be pretty straightforward:

> To prevent the exception and keep the old behavior, set allow_multiple_selected to True.

But we'd still have security issues. Better do this: https://docs.djangoproject.com/en/4.2/topics/http/file-uploads/#uploading-multiple-files 

```
Traceback (most recent call last):
  File "src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/check.py", line 63, in handle
    self.check(
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line [7](https://github.com/bytedeck/bytedeck/actions/runs/4922947054/jobs/8794229722?pr=1352#step:6:8)6, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.[8](https://github.com/bytedeck/bytedeck/actions/runs/4922947054/jobs/8794229722?pr=1352#step:6:9)/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 5[9](https://github.com/bytedeck/bytedeck/actions/runs/4922947054/jobs/8794229722?pr=1352#step:6:10)5, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line [10](https://github.com/bytedeck/bytedeck/actions/runs/4922947054/jobs/8794229722?pr=1352#step:6:11)14, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/src/hackerspace_online/urls.py", line 40, in <module>
    url(r'^quests/', include('quest_manager.urls', namespace='quests')),
  File "/usr/local/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line [12](https://github.com/bytedeck/bytedeck/actions/runs/4922947054/jobs/8794229722?pr=1352#step:6:13)7, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/src/quest_manager/urls.py", line 16, in <module>
    from quest_manager import views
  File "/app/src/quest_manager/views.py", line 32, in <module>
    from .forms import (QuestForm, SubmissionForm, SubmissionFormCustomXP, SubmissionFormStaff,
  File "/app/src/quest_manager/forms.py", line 2[13](https://github.com/bytedeck/bytedeck/actions/runs/4922947054/jobs/8794229722?pr=1352#step:6:14), in <module>
    class SubmissionForm(forms.Form):
  File "/app/src/quest_manager/forms.py", line 2[18](https://github.com/bytedeck/bytedeck/actions/runs/4922947054/jobs/8794229722?pr=1352#step:6:19), in SubmissionForm
    widget=forms.ClearableFileInput(attrs={'multiple': True}),
  File "/usr/local/lib/python3.8/site-packages/django/forms/widgets.py", line [39](https://github.com/bytedeck/bytedeck/actions/runs/4922947054/jobs/8794229722?pr=1352#step:6:40)1, in __init__
    raise ValueError(
ValueError: ClearableFileInput doesn't support uploading multiple files.
```

**Comment by demonshreder** [comment]
Facing this error with 4.2.1 & 4.2.2 but not with 4.2.0
