### ISSUE TITLE
Re-creating database errors due to socialaccount

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1379]
I deleted my postgres volume to start a fresh db, and when creating a new deck I get this:

web_1          | [1/1 (100%) standard:hackerspace]   Applying sites.0002_alter_domain_unique...
web_1          | [1/1 (100%) standard:hackerspace]   Applying socialaccount.0001_initial...
web_1          | Internal Server Error: /accounts/login/
web_1          | Traceback (most recent call last):
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
web_1          |     response = get_response(request)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
web_1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
web_1          |     return self.dispatch(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
web_1          |     return bound_method(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
web_1          |     return view(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/allauth/account/views.py", line 149, in dispatch
web_1          |     return super(LoginView, self).dispatch(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/allauth/account/views.py", line 77, in dispatch
web_1          |     response = super(RedirectAuthenticatedUserMixin, self).dispatch(
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
web_1          |     return handler(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/allauth/account/views.py", line 97, in get
web_1          |     return _ajax_response(
web_1          |   File "/usr/local/lib/python3.8/site-packages/allauth/account/views.py", line 64, in _ajax_response
web_1          |     response = adapter.ajax_response(
web_1          |   File "/usr/local/lib/python3.8/site-packages/allauth/account/adapter.py", line 358, in ajax_response
web_1          |     response.render()
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
web_1          |     self.content = self.rendered_content
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
web_1          |     return template.render(context, self._request)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
web_1          |     return self.template.render(context)
web_1          |   File "/usr/local/lib/python3.8/site-packages/template_timings_panel/panels/TemplateTimings.py", line 139, in timing_hook
web_1          |     result = func(self, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/template_timings_panel/panels/TemplateTimings.py", line 139, in timing_hook
web_1          |     result = func(self, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/template_timings_panel/panels/TemplateTimings.py", line 139, in timing_hook
web_1          |     result = func(self, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 168, in render
web_1          |     with context.bind_template(self):
web_1          |   File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
web_1          |     return next(self.gen)
web_1          |   File "/usr/local/lib/python3.8/site-packages/debug_toolbar/panels/templates/panel.py", line 45, in _request_context_bind_template
web_1          |     context = processor(self.request)
web_1          |   File "/app/src/hackerspace_online/context_processors.py", line 19, in config
web_1          |     return {"config": SiteConfig.get()}
web_1          |   File "/app/src/siteconfig/models.py", line 317, in get
web_1          |     siteconfig = cls.objects.select_related('deck_ai', 'active_semester').get()
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
web_1          |     raise self.model.DoesNotExist(
web_1          | siteconfig.models.SiteConfig.DoesNotExist: SiteConfig matching query does not exist.
web_1          | Internal Server Error: /accounts/login/
web_1          | Traceback (most recent call last):
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
web_1          |     response = get_response(request)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
web_1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
web_1          |     return self.dispatch(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
web_1          |     return bound_method(*args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
web_1          |     return view(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/allauth/account/views.py", line 149, in dispatch
web_1          |     return super(LoginView, self).dispatch(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/allauth/account/views.py", line 77, in dispatch
web_1          |     response = super(RedirectAuthenticatedUserMixin, self).dispatch(
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
web_1          |     return handler(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/allauth/account/views.py", line 97, in get
web_1          |     return _ajax_response(
web_1          |   File "/usr/local/lib/python3.8/site-packages/allauth/account/views.py", line 64, in _ajax_response
web_1          |     response = adapter.ajax_response(
web_1          |   File "/usr/local/lib/python3.8/site-packages/allauth/account/adapter.py", line 358, in ajax_response
web_1          |     response.render()
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
web_1          |     self.content = self.rendered_content
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
web_1          |     return template.render(context, self._request)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
web_1          |     return self.template.render(context)
web_1          |   File "/usr/local/lib/python3.8/site-packages/template_timings_panel/panels/TemplateTimings.py", line 139, in timing_hook
web_1          |     result = func(self, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/template_timings_panel/panels/TemplateTimings.py", line 139, in timing_hook
web_1          |     result = func(self, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 168, in render
web_1          |     with context.bind_template(self):
web_1          |   File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
web_1          |     return next(self.gen)
web_1          |   File "/usr/local/lib/python3.8/site-packages/debug_toolbar/panels/templates/panel.py", line 45, in _request_context_bind_template
web_1          |     context = processor(self.request)
web_1          |   File "/app/src/hackerspace_online/context_processors.py", line 19, in config
web_1          |     return {"config": SiteConfig.get()}
web_1          |   File "/app/src/siteconfig/models.py", line 317, in get
web_1          |     siteconfig = cls.objects.select_related('deck_ai', 'active_semester').get()
web_1          |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
web_1          |     raise self.model.DoesNotExist(
web_1          | siteconfig.models.SiteConfig.DoesNotExist: SiteConfig matching query does not exist.
web_1          | [1/1 (100%) standard:hackerspace]  OK
web_1          | [1/1 (100%) standard:hackerspace]   Applying socialaccount.0002_token_max_lengths...
web_1          | [1/1 (100%) standard:hackerspace]  OK
web_1          | [1/1 (100%) standard:hackerspace]   Applying socialaccount.0003_extra_data_default_dict...
web_1          | [1/1 (100%) standard:hackerspace]  OK
web_1          | [1/1 (100%) standard:hackerspace]   Applying tenant.0001_initial...
web_1          | [1/1 (100%) standard:hackerspace]  OK
web_1          | [1/1 (100%) standard:hackerspace]   Applying tenant.0002_tenant_desc...
web_1          | [1/1 (100%) standard:hackerspace]  OK
web_1          | [1/1 (100%) standard:hackerspace]   Applying tenant.0003_auto_20200405_0647...

**Comment by tylerecouture** [comment]
Nope. my bad.
