### ISSUE TITLE
[Bytedeck]ERROR (EXTERNAL IP): Internal Server Error: /notifications/read/465/

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1446]
`raise HttpResponseRedirect(reverse('notifications:list'))` <-- should be return not raise?

TypeError at /notifications/read/465/
exceptions must derive from BaseException

```
Traceback (most recent call last):
  File "/app/src/notifications/views.py", line 75, in read
    raise Http404

During handling of the above exception (), another exception occurred:
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/src/tenant/views.py", line 37, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/src/notifications/views.py", line 78, in read
    raise HttpResponseRedirect(reverse('notifications:list'))

Exception Type: TypeError at /notifications/read/465/
Exception Value: exceptions must derive from BaseException
```

**Comment by tylerecouture** [comment]
@Dylan-RG-Patterson this is bad code written 8 years ago when I didn't know what I was doing.

I ASSUME the exception it is trying to catch is if the Notification doesn't exist, on this line:
`notification = Notification.objects.get(id=id)`

Because manual url entry, or the notification was deleted, or some other reason.  I'm not sure why I didn't just get_object_or404 this. 

So to reproduce, you could go to:

`/notifications/read/99999999/`

Looking again at this code, the except line needs to be fixed to be specific to what exception we are explicitly catching:

`except Notification.DoesNotExist:`

Then we can remove the TODO comment.

**Comment by tylerecouture** [comment]
closed by https://github.com/bytedeck/bytedeck/pull/1458
