### ISSUE TITLE
Exception Type: FieldError at /select2/fields/auto.json - Exception Value: Cannot resolve keyword 'first_name' into field

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1571]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_select2/views.py", line 37, in get
    self.object_list = self.get_queryset()
  File "/usr/local/lib/python3.8/site-packages/django_select2/views.py", line 57, in get_queryset
    return self.widget.filter_queryset(self.term, self.queryset, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_select2/forms.py", line 406, in filter_queryset
    return queryset.filter(select).distinct()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1288, in build_filter
    return self._add_q(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1309, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1135, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1562, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "

Exception Type: FieldError at /select2/fields/auto.json
Exception Value: Cannot resolve keyword 'first_name' into field. Choices are: alias, avatar, banned_from_comments, custom_stylesheet, dark_theme, datetime_created, get_announcements_by_email, get_messages_by_email, get_notifications_by_email, grad_year, hidden_quests, id, intro_tour_completed, is_TA, is_test_account, mark_cached, not_earning_xp, preferred_internal_only, preferred_name, silent_mode, time_of_last_submission, user, user_id, visible_to_other_students, xp_cached
Request information:

**Comment by tylerecouture** [comment]
HTTP_REFERER = 'https://studiotyee.bytedeck.com/badges/151/grant/bulk/'

**Comment by tylerecouture** [comment]
Is this another item fixed when we run #1635 ?
