### ISSUE TITLE
Upgrade to Django 3.2 LTS

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#903]
Current Django 2.2 LTS end of support is Apr 2022

Need to upgrade to Django 3.2 LTS (support to Apr 2024)

**Comment by yujinyuz** [comment]
@tylerecouture I am currently blocked with this one since I'm getting this error:

```
** Running initial migrations on the public schema...
Traceback (most recent call last):
  File "src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/me/.local/share/virtualenvs/bytedeck/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/me/.local/share/virtualenvs/bytedeck/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/me/.local/share/virtualenvs/bytedeck/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/me/.local/share/virtualenvs/bytedeck/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/me/Sources/github.com/yujinyuz/bytedeck/src/hackerspace_online/management/commands/initdb.py", line 34, in handle
    call_command("migrate_schemas", "--shared")
  File "/Users/me/.local/share/virtualenvs/bytedeck/lib/python3.8/site-packages/django/core/management/__init__.py", line 116, in call_command
    parser = command.create_parser('', command_name)
  File "/Users/me/.local/share/virtualenvs/bytedeck/lib/python3.8/site-packages/django/core/management/base.py", line 320, in create_parser
    self.add_arguments(parser)
  File "/Users/me/.local/share/virtualenvs/bytedeck/lib/python3.8/site-packages/tenant_schemas/management/commands/migrate_schemas.py", line 20, in add_arguments
    command.add_arguments(parser)
  File "/Users/me/.local/share/virtualenvs/bytedeck/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 26, in add_arguments
    parser.add_argument(
  File "/Users/me/.asdf/installs/python/3.8.10/lib/python3.8/argparse.py", line 1386, in add_argument
    return self._add_action(action)
  File "/Users/me/.asdf/installs/python/3.8.10/lib/python3.8/argparse.py", line 1749, in _add_action
    self._optionals._add_action(action)
  File "/Users/me/.asdf/installs/python/3.8.10/lib/python3.8/argparse.py", line 1590, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/Users/me/.asdf/installs/python/3.8.10/lib/python3.8/argparse.py", line 1400, in _add_action
    self._check_conflict(action)
  File "/Users/me/.asdf/installs/python/3.8.10/lib/python3.8/argparse.py", line 1539, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/Users/me/.asdf/installs/python/3.8.10/lib/python3.8/argparse.py", line 1548, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --skip-checks: conflicting option string: --skip-checks
```
It's a known issue: https://github.com/bernardopires/django-tenant-schemas/pull/650

They suggest migrating to `django-tenants`. I have an existing PR here: #648 but it needs to be updated.

Let me know whether we should proceed with migrating to django-tenants

**Comment by tylerecouture** [comment]
Yes, please update #648
